version: 2
jobs:
  build:
    docker:
      - image: circleci/node:18.16.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run compile
      - run: npm run lint
      - run: npm run format
