version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.18.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run type-check
      - run: npm run lint
      - run: npm run format
